apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  securityContext:
    fsGroup: 1000

  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - containerPort: 8080

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false

    volumeMounts:
      - name: jenkins-ebs
        mountPath: /var/jenkins_home

  volumes:
  - name: jenkins-ebs
    persistentVolumeClaim:
      claimName: jenkins-ebs-pvc
